# Generated by Django 2.2.1 on 2019-05-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='observações',
            field=models.TextField(blank=True, null=True),
        ),
    ]
