# Generated by Django 2.2.1 on 2019-05-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20190517_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transacao',
            new_name='puta',
        ),
        migrations.AlterModelOptions(
            name='puta',
            options={},
        ),
    ]
