# Generated by Django 2.2.1 on 2019-05-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20190517_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puta',
            name='data',
        ),
    ]
