# Generated by Django 2.2.1 on 2019-05-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_remove_puta_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puta',
            old_name='observações',
            new_name='observacoes',
        ),
    ]
