# Generated by Django 2.2.1 on 2019-05-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_auto_20190517_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puta',
            old_name='descricao',
            new_name='nome',
        ),
    ]
