# Generated by Django 2.2.1 on 2019-05-18 18:48

import django.conf.urls.static
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0010_auto_20190518_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to={django.conf.urls.static.static, '/images'}),
        ),
    ]
