# Generated by Django 2.2.1 on 2019-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_auto_20190518_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
