# Generated by Django 2.2.1 on 2019-05-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_auto_20190518_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='Foto',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
