# Generated by Django 2.2.1 on 2019-05-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_auto_20190522_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='Foto',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
