# Generated by Django 2.2.1 on 2019-05-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0014_auto_20190522_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='Foto',
            field=models.FileField(upload_to='images/'),
        ),
    ]
