# Generated by Django 2.2.1 on 2019-06-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
