# Generated by Django 2.2.1 on 2019-06-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Nome',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='Observacoes',
            field=models.TextField(blank=True, default='default', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Foto',
            field=models.FileField(default='default.jpg', upload_to='images/'),
        ),
    ]
