# Generated by Django 2.2.1 on 2019-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0019_auto_20190602_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Foto',
            field=models.FileField(default='default.jpg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
