# Generated by Django 2.2.1 on 2019-06-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0020_auto_20190605_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_func', models.CharField(max_length=200)),
                ('ID_atv', models.CharField(max_length=200)),
                ('Data', models.CharField(max_length=200)),
            ],
        ),
    ]
