# Generated by Django 2.2.1 on 2019-06-12 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0023_auto_20190610_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.Categoria'),
        ),
    ]
