# Generated by Django 2.2.1 on 2019-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0024_profile_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='pont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ColdCall', models.BooleanField(default=False)),
                ('LALA', models.BooleanField(default=False)),
            ],
        ),
    ]
